version: '2.4'
services:
  mysql_56:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 10306:3306
    volumes:
      - mysql_56:/var/lib/mysql
    environment:
      # Set in /etc/environment
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  mysql_57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 10307:3306
    volumes:
      - mysql_57:/var/lib/mysql
    environment:
      # Set in /etc/environment
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  mysql_80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 10308:3306
    volumes:
      - mysql_80:/var/lib/mysql
    environment:
      # Set in /etc/environment
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
volumes:
  mysql_56:
  mysql_57:
  mysql_80:
